name: yeast
channels:
- defaults
- conda-forge
dependencies:
- flake8=3.7.9
- inflection=0.3.1
- pandas=1.0.3
- pip=19.3.1
- pep8=1.7.1
- pytest=5.3.2
- pytest-cov=2.8.1
- python=3.7.7
- pip:
     - pytest-pythonpath==0.7.3
     - mkdocs==1.0.4
     - mkautodoc==0.1.0
