site_name: Yeast
site_description: A Python data processing engine for modeling or visualization
theme:
  name: gitbook

repo_name: iuga/yeast
repo_url: https://github.com/iuga/yeast

use_directory_urls: false
nav:
  - Yeast:
    - Home: index.md
  - Getting Started:
    - 5 Minute Introduction: introduction.md
    - Methods for Selecting Variables: selectors.md
    - Methods for Transforming Variables: transformers.md
    - Methods for Groups and Aggregations: aggregations.md
    - Join two DataFrames together: merge.md
  - Developers API:
    - Step Reference: reference.md
    - Custom Steps: extensions.md
    - Roadmap: roadmap.md
  - Examples:
    - San Francisco Crime: examples/san_francisco_crime.md
plugins: []
extra_css:
    - extra.css
    - styles.css
markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
  - toc:
        permalink: True
extra:
  logo:
    logo.jpg
  include_toc: yes
  show_powered_by: false
